### PR TITLE
Improved on.data handling for reading.

### PR DESCRIPTION
**Pull request by mnemo70**
My try at fixing the connection problem. This only considers reading data from the heatpump at the moment. I didn't change much, but this version now works in my Node-RED without crashing.

### CODE REVIEW

**Comment by UncleSamSwiss** [comment]
@mnemo70 Thanks a lot.
Looks very good. I left my adapter running for several hours with these changes and I haven't seen a single exception.
I hope this gets merged back quickly and ends up in a new release soon.

**Comment by coolchip** [comment]
Thank you. Will test it on my device. If it is working I will merge it.

**Comment by mnemo70** [comment]
Write function has been corrected also. It collects messages now and stores the client to a different variable, so it does not overwrite the read client instance when both are handled concurrently.

**Comment by coolchip** [comment]
Works for also for me. Great work. Will test it till tomorrow. Then I will merge and create a new package version.

**Pull request merged**
