### PR TITLE
add constants for module errors

### PR DESCRIPTION
**Pull request by bakito**
Hi coolchip

I updated my pimatic module with your version 1.0.0 and had to modify the error handling of the busy state since you renamed it after 0.12.

It would be nice if I could refer to the errors used in your library by accessing it via constant.

I'm not sure if my implementation is the best. 
What do your think?

### CODE REVIEW

**Comment by coolchip** [comment]
Hey, I think I understand what you want. But the Impementation is not the best. I'll see how I can help you anyway.

**Comment by coolchip** [comment]
If I see that correctly you need in your pimatic only the "heatpump busy" signal. I think you don't need that fancy "Unexpected Data". 
What, if I give you every time the this object you expected and add the heatpump state to this object. 
``
{
values: [ ... ],
parameters: [ ... ],
heatpumpState: 'ready'
}
``

**Comment by bakito** [comment]
Are you able to return any valid data if the heatpump is busy?
Or would then everything else be empty expect the heatpumpState?
It does not matter how I can receive the busy state. An error is also ok for me. My problem is that I would like to identify this error explicitly. That's where the Idea of a constant that I could reuse come from.

I'm not an experienced JavaScript developer, therefore my clumsy approach.

**Comment by coolchip** [comment]
Very old. Closing this. If there is any new idea, let me know.

**Pull request closed without merging**
